# Generated by Django 5.2.17 on 2026-09-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_desk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderecord',
            name='action',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='traderecord',
            name='ticker',
            field=models.CharField(max_length=6),
        ),
    ]
